<?php
namespace phMagick\Core;

/**
 * Test class for Action.
 * Generated by PHPUnit on 2011-12-12 at 15:59:41.
 */
class foo extends Action
{

    public function getCommand()
    {
        return true;
    }
}

class ActionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Action
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */

    protected function setUp()
    {
        $this->object = new foo(null, null);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */

    protected function tearDown()
    {
    }

    public function testSetSource()
    {
        $this->object->setSource('foo');
        $this->assertEquals('foo', $this->object->getSource());
    }

    public function testSetDestination()
    {
        $this->object->setDestination('foo');
        $this->assertEquals('foo', $this->object->getDestination());
    }

    public function testGetCommand()
    {
        $this->assertTrue($this->object->getCommand());
    }
}
?>
