<?php
namespace phMagick\Core;



/**
 * Test class for System.
 * Generated by PHPUnit on 2011-12-11 at 22:01:02.
 */
class SystemTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var System
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new System;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testGetRunner()
    {
        $this->assertTrue($this->object->getRunner() instanceof \phMagick\Core\Runner);
    }

    public function testGetLogger()
    {
        $this->assertTrue($this->object->getLogger() instanceof \phMagick\Core\Logger);
    }

    public function testGetSettings()
    {
        $this->assertTrue($this->object->getSettings() instanceof \phMagick\Core\Settings);
    }

//     /**
//      * @covers {className}::{origMethodName}
//      * @todo Implement testAdd().
//      */
//     public function testAdd()
//     {
//         // Remove the following lines when you implement this test.
//         $this->markTestIncomplete(
//           'This test has not been implemented yet.'
//         );
//     }

//     /**
//      * @covers {className}::{origMethodName}
//      * @todo Implement testExecute().
//      */
//     public function testExecute()
//     {
//         // Remove the following lines when you implement this test.
//         $this->markTestIncomplete(
//           'This test has not been implemented yet.'
//         );
//     }
}
?>
